### PR TITLE
feat: export multi-grid projects

### LINKED ISSUE #136: feat: export multi-grid projects

### PR DESCRIPTION
**Pull request by sasanjac**
Fixes #136

### CODE REVIEW

**Comment by SebastianDD** [comment]
should include fixes #164 

Also how is the file name created? --> project_name + study case name

**Comment by SebastianDD** [comment]
control example needs to be adjusted

**Comment by sasanjac** [comment]
> control example needs to be adjusted

what has to be done here?

**Comment by SebastianDD** [comment]
> > control example needs to be adjusted
> 
> what has to be done here?

update calls of interface functions and adds grid_name to some function calls

@sasanjac Execution of control example as own proccess does not work right now, seems not to start the wohle interface

**Comment by SebastianDD** [comment]
TODO fix: export objects, regardless of "out_of _service"

**Review by SebastianDD — APPROVED** [review]

**Pull request merged**
