### PR TITLE
fix: transformer data export incomplete

### LINKED ISSUE #158: fix: transformer data export incomplete
I just discovered that the transformer data is not exported right. (Winding 2 r0, r1, x0, x1 missing (?), re and xe missing / null) 
The exported data is:
grafik
There are no values for  r0, r1, x0, x1 for winding 2 or are they specified for the whole transformer (which would be more plausible to me), if so, why are they stored under windings and not with p_fe and i_0 directly under transformer
grafik
In addition re and xe are missing 
grafik

### PR DESCRIPTION
**Pull request by SebastianDD**
Fixes #158

### CODE REVIEW

**Comment by SebastianDD** [comment]
@sasanjac 
for the user it is not apparent, that hte thrown KeyError is caused by psdm.
maybe extend the Error message?

**Comment by sasanjac** [comment]
> @sasanjac for the user it is not apparent, that hte thrown KeyError is caused by psdm. maybe extend the Error message?

No I wouldn't. I think the error message is concise enough to understand whats the problem.
If we did that, I would just not catch the error and let the user see the original error from psdm.

**Comment by SebastianDD** [comment]
Todo before merge: new export of grid

**Review by FiedLa — APPROVED** [review]

**Comment by SebastianDD** [comment]
[psdm issue 57](https://github.com/ieeh-tu-dresden/power-system-data-model/issues/57) has to be solved first

**Review by sasanjac — APPROVED** [review]

**Pull request merged**
